source 'https://github.com/CocoaPods/Specs.git'

target 'ROSelector', :exclusive => true do
  pod "ROSelector", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ROSelector", :path => "../"

  
end
